### PR TITLE
Draft: Changes required for repository inclusion

### PR DESCRIPTION
**Pull request by mintsoft**
I've had to bump the version number so it follows the matrix numbering. The PR into the repo is currently open, so if other things are raised I'll put them against this and let you know when it's "done" as it were.

### CODE REVIEW

**Comment by TheAssassin** [comment]
I've made the PR a draft now so it won't be merged prematurely. Please let me know once you're ready. We can also merge more than one PR.

**Comment by mintsoft** [comment]
Hmm, think I've nearly finished here, just need to switch the configuration file format to the new one and localise it then we're probably ready to go.

I am hitting something odd at the moment when I search for videos  that I can't see what I've done wrong at the moment, however I've not done any debugging yet and I've run out of time for today thus far:

```
2022-03-27 15:51:07.529 T:20296   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: parse_video_list_response() takes 1 positional argument but 2 were given
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Rob\AppData\Roaming\Kodi\addons\plugin.video.invidious\resources\lib\invidious_addon.py", line 18, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\Rob\AppData\Roaming\Kodi\addons\plugin.video.invidious\resources\lib\invidious_addon.py", line 14, in main
                                                       return plugin.run()
                                                     File "C:\Users\Rob\AppData\Roaming\Kodi\addons\plugin.video.invidious\resources\lib\invidious_plugin.py", line 160, in run
                                                       self.display_search()
                                                     File "C:\Users\Rob\AppData\Roaming\Kodi\addons\plugin.video.invidious\resources\lib\invidious_plugin.py", line 82, in display_search
                                                       results = self.api_client.search(search_input)
                                                     File "C:\Users\Rob\AppData\Roaming\Kodi\addons\plugin.video.invidious\resources\lib\invidious_api.py", line 79, in search
                                                       return self.parse_video_list_response(response)
                                                   TypeError: parse_video_list_response() takes 1 positional argument but 2 were given
                                                   -->End of Python script error report<--
```

**Comment by TheAssassin** [comment]
https://github.com/mintsoft/kodi-invidious-plugin/blob/master/resources/lib/invidious_api.py#L46, the function definition is missing `self` as the first parameter. Please fix that. It'll work then.

**Comment by mintsoft** [comment]
> https://github.com/mintsoft/kodi-invidious-plugin/blob/master/resources/lib/invidious_api.py#L46, the function definition is missing `self` as the first parameter. Please fix that. It'll work then.

Of course! Thanks :)

**Comment by mintsoft** [comment]
I think this is all done, I'm just waiting on the thumbs up on the other PR. I think I'd like to move all the code apart from README.md into a subfolder called `plugin.video.invidious` so that I can easily filter out the README.md and it means there's a totally correct folder structure within the repo for manually installing from zip etc. Thoughts?

**Comment by TheAssassin** [comment]
Sure, let's do that. But in a subsequent PR.

**Comment by mintsoft** [comment]
I think this is good to go judging by the latest response on https://github.com/xbmc/repo-plugins/pull/3927. I think they want to see these changes get merged in first then they're happy.

**Comment by TheAssassin** [comment]
Thank you @mintsoft!

**Pull request merged**
